# Generated by Django 4.2.7 on 2025-07-03 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('reports', 'Crime Reports'), ('evidence', 'Evidence Files'), ('audit_logs', 'Audit Logs'), ('notifications', 'Notifications'), ('user_data', 'User Data'), ('statistics', 'Statistics')], max_length=20, unique=True)),
                ('retention_period', models.CharField(choices=[('1_year', '1 Year'), ('3_years', '3 Years'), ('5_years', '5 Years'), ('7_years', '7 Years'), ('10_years', '10 Years'), ('permanent', 'Permanent')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('legal_basis', models.TextField(blank=True)),
                ('auto_cleanup', models.BooleanField(default=True)),
                ('archive_before_deletion', models.BooleanField(default=True)),
                ('archive_location', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Retention Policy',
                'verbose_name_plural': 'Data Retention Policies',
                'db_table': 'data_retention_policies',
            },
        ),
        migrations.CreateModel(
            name='FileScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error'), ('quarantined', 'Quarantined')], default='pending', max_length=20)),
                ('scan_result', models.JSONField(default=dict)),
                ('scan_error', models.TextField(blank=True)),
                ('threats_found', models.JSONField(default=list)),
                ('threat_count', models.PositiveIntegerField(default=0)),
                ('scanned_by', models.CharField(default='clamav', max_length=50)),
                ('scan_duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_scans',
                'indexes': [models.Index(fields=['file_hash'], name='file_scans_file_ha_c28e97_idx'), models.Index(fields=['scan_status'], name='file_scans_scan_st_24d582_idx'), models.Index(fields=['created_at'], name='file_scans_created_cc6dd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('requires_review', 'Requires Review')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('custody_chain', models.JSONField(default=list)),
                ('digital_signature', models.CharField(blank=True, max_length=128)),
                ('signature_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='reports.reportevidence')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_verified_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidence_verification',
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('failed_login', 'Failed Login'), ('password_change', 'Password Change'), ('file_upload', 'File Upload'), ('file_download', 'File Download'), ('evidence_access', 'Evidence Access'), ('report_access', 'Report Access'), ('status_change', 'Status Change'), ('assignment', 'Report Assignment'), ('admin_action', 'Admin Action'), ('data_export', 'Data Export'), ('data_deletion', 'Data Deletion')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.reportevidence')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.crimereport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='security_au_event_t_ea81bb_idx'), models.Index(fields=['user', 'timestamp'], name='security_au_user_id_840f4f_idx'), models.Index(fields=['severity', 'timestamp'], name='security_au_severit_381e37_idx'), models.Index(fields=['ip_address', 'timestamp'], name='security_au_ip_addr_292fe7_idx')],
            },
        ),
    ]
