# Generated by Django 4.2.7 on 2025-07-03 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('status_change', 'Status Change'), ('assignment', 'Assignment'), ('comment', 'New Comment'), ('evidence', 'Evidence Added'), ('reminder', 'Reminder'), ('welcome', 'Welcome'), ('password_reset', 'Password Reset'), ('verification', 'Account Verification')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('email_template', models.TextField()),
                ('sms_template', models.TextField(blank=True)),
                ('in_app_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('variables', models.JSONField(default=dict, help_text='Available template variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_status_updates', models.BooleanField(default=True)),
                ('email_assignments', models.BooleanField(default=True)),
                ('email_comments', models.BooleanField(default=True)),
                ('email_reminders', models.BooleanField(default=False)),
                ('email_marketing', models.BooleanField(default=False)),
                ('sms_status_updates', models.BooleanField(default=False)),
                ('sms_assignments', models.BooleanField(default=False)),
                ('sms_urgent', models.BooleanField(default=True)),
                ('in_app_status_updates', models.BooleanField(default=True)),
                ('in_app_assignments', models.BooleanField(default=True)),
                ('in_app_comments', models.BooleanField(default=True)),
                ('in_app_reminders', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('status_change', 'Status Change'), ('assignment', 'Assignment'), ('comment', 'New Comment'), ('evidence', 'Evidence Added'), ('reminder', 'Reminder'), ('welcome', 'Welcome'), ('password_reset', 'Password Reset'), ('verification', 'Account Verification')], max_length=20)),
                ('send_email', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_in_app', models.BooleanField(default=True)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('sms_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('in_app_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('in_app_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True)),
                ('sms_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.crimereport')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_63f199_idx'), models.Index(fields=['email_status', 'sms_status'], name='notificatio_email_s_42a851_idx'), models.Index(fields=['scheduled_at'], name='notificatio_schedul_2a5c00_idx')],
            },
        ),
    ]
