# Generated by Django 5.2.3 on 2025-07-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
