# Generated by Django 5.2.3 on 2025-07-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tablebooking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
