# Generated by Django 5.2.3 on 2025-07-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tablebooking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
