# Generated by Django 5.2.3 on 2025-07-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_tablebooking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
