# Generated by Django 5.2.3 on 2025-07-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_tablebooking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='table_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
