# Generated by Django 5.2.3 on 2025-07-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_searchquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About RTB - Restaurant Table Booking', max_length=200)),
                ('description', models.TextField(default="\n      At RTB, we believe dining should be more than just food – it should be an experience. \n      Our platform connects food lovers with the finest restaurants, allowing them to book tables effortlessly from the comfort of their homes.\n      \n      Whether you're planning a romantic dinner, a family celebration, or a corporate lunch, our hand-picked list of restaurants offers something for every taste and occasion.\n      \n      With real-time availability, curated menus, and trusted reviews, RTB is your reliable partner for seamless dining experiences.\n    ")),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
    ]
