# Generated by Django 4.2.7 on 2025-07-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='access_level',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('restricted', 'Restricted'), ('confidential', 'Confidential')], default='restricted', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.crimecategory'),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='incident_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='incident_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='priority',
            field=models.CharField(blank=True, choices=[('normal', 'Normal (सामान्य)'), ('medium', 'Medium (मध्यम)'), ('critical', 'Critical (गंभीर)'), ('sensitive', 'Sensitive (संवेदनशील)')], default='medium', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='reporter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('assigned', 'Assigned to Officer'), ('investigating', 'Under Investigation'), ('pending_evidence', 'Pending Evidence'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='submitted', max_length=20, null=True),
        ),
    ]
