# Generated by Django 5.2.3 on 2025-06-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzone_api', '0006_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('Basic', 'Basic Plan'), ('Standard', 'Standard Plan'), ('Premium', 'Premium Plan')], max_length=20),
        ),
    ]
