# Generated by Django 5.2.3 on 2025-06-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzone_api', '0007_alter_plan_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10),
        ),
    ]
