# Generated by Django 4.2.7 on 2025-07-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language_preference',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('public', 'Public Citizen'), ('police', 'Police Officer'), ('admin', 'Administrator')], default='public', max_length=20),
        ),
    ]
