# Generated by Django 4.2.7 on 2025-07-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_language_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badge_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
