# Generated by Django 4.2.7 on 2025-07-16 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_station_crimereport_station'),
        ('authentication', '0005_user_badge_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='reports.station'),
        ),
    ]
