# Generated by Django 5.2.3 on 2025-06-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
