# Generated by Django 5.2.3 on 2025-06-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
