# Generated by Django 5.2.3 on 2025-07-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
