# Generated by Django 4.2.7 on 2025-07-03 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('chart', 'Chart'), ('metric', 'Metric'), ('table', 'Table'), ('map', 'Map')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict)),
                ('data_source', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('refresh_interval', models.PositiveIntegerField(default=3600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'public_dashboard',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransparencyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly Report'), ('quarterly', 'Quarterly Report'), ('annual', 'Annual Report'), ('special', 'Special Report')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('summary', models.TextField()),
                ('key_findings', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('statistics_snapshot', models.JSONField(default=dict)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='transparency_reports/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transparency_reports',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='CrimeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('total_reports', models.PositiveIntegerField(default=0)),
                ('resolved_reports', models.PositiveIntegerField(default=0)),
                ('pending_reports', models.PositiveIntegerField(default=0)),
                ('rejected_reports', models.PositiveIntegerField(default=0)),
                ('category_breakdown', models.JSONField(default=dict)),
                ('priority_breakdown', models.JSONField(default=dict)),
                ('avg_resolution_time_hours', models.FloatField(default=0.0)),
                ('avg_response_time_hours', models.FloatField(default=0.0)),
                ('location_breakdown', models.JSONField(default=dict)),
                ('officer_assignments', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crime_statistics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'period_type'], name='crime_stati_date_ece443_idx')],
            },
        ),
    ]
