
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                        new LoginPg().setVisible(true);
                }
        });


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        closebtn = new javax.swing.JButton();
        studReg = new javax.swing.JButton();
        addbkBtn = new javax.swing.JButton();
        issuebkBtn = new javax.swing.JButton();
        rtnBkBtn = new javax.swing.JButton();
        lgoutBtn = new javax.swing.JButton();
        adminBtn = new javax.swing.JButton();
        books_av = new javax.swing.JButton();
        contactus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 766));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 766));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1329, 0, 37, 36));

        studReg.setBackground(new java.awt.Color(255, 0, 0));
        studReg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        studReg.setForeground(new java.awt.Color(255, 255, 255));
        studReg.setText("Student Registration");
        studReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studRegActionPerformed(evt);
            }
        });
        getContentPane().add(studReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 260, 42));

        addbkBtn.setBackground(new java.awt.Color(255, 0, 0));
        addbkBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addbkBtn.setForeground(new java.awt.Color(255, 255, 255));
        addbkBtn.setText("Add Books");
        addbkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbkBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 260, 42));

        issuebkBtn.setBackground(new java.awt.Color(255, 0, 0));
        issuebkBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        issuebkBtn.setForeground(new java.awt.Color(255, 255, 255));
        issuebkBtn.setText("Issue Book");
        issuebkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuebkBtnActionPerformed(evt);
            }
        });
        getContentPane().add(issuebkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 330, 270, 42));

        rtnBkBtn.setBackground(new java.awt.Color(255, 0, 0));
        rtnBkBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rtnBkBtn.setForeground(new java.awt.Color(255, 255, 255));
        rtnBkBtn.setText("Return Book");
        rtnBkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtnBkBtnActionPerformed(evt);
            }
        });
        getContentPane().add(rtnBkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, 260, 40));

        lgoutBtn.setBackground(new java.awt.Color(204, 204, 255));
        lgoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.jpg"))); // NOI18N
        lgoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(lgoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 550, 270, -1));

        adminBtn.setBackground(new java.awt.Color(255, 0, 0));
        adminBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adminBtn.setForeground(new java.awt.Color(255, 255, 255));
        adminBtn.setText("Admin ");
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });
        getContentPane().add(adminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 60, 280, 40));

        books_av.setBackground(new java.awt.Color(255, 0, 0));
        books_av.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        books_av.setForeground(new java.awt.Color(255, 255, 255));
        books_av.setText("Books Available");
        books_av.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                books_avActionPerformed(evt);
            }
        });
        getContentPane().add(books_av, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 200, 270, 40));

        contactus.setBackground(new java.awt.Color(255, 0, 0));
        contactus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        contactus.setForeground(new java.awt.Color(255, 255, 255));
        contactus.setText("Contact us");
        contactus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactusActionPerformed(evt);
            }
        });
        getContentPane().add(contactus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 480, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeBg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studRegActionPerformed
        new StudentRegis().setVisible(true);
    }//GEN-LAST:event_studRegActionPerformed

    private void issuebkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuebkBtnActionPerformed
        new IssueBook().setVisible(true);
    }//GEN-LAST:event_issuebkBtnActionPerformed

    private void addbkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbkBtnActionPerformed
        new AddBooks().setVisible(true);
    }//GEN-LAST:event_addbkBtnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Do you really want to exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);  // This will close the whole app
        }
    }//GEN-LAST:event_closebtnActionPerformed

    private void rtnBkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtnBkBtnActionPerformed
        new ReturnBookPg().setVisible(true);
    }//GEN-LAST:event_rtnBkBtnActionPerformed

    private void lgoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgoutBtnActionPerformed
        int yes = JOptionPane.showConfirmDialog(Home.this ,"Are you sure you really want to Logout from this application", "Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE); 
        if(yes == JOptionPane.YES_NO_OPTION)
                new LoginPg().setVisible(true);
    }//GEN-LAST:event_lgoutBtnActionPerformed

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
       
        
        new AdminPg().setVisible(true);
    }//GEN-LAST:event_adminBtnActionPerformed

    private void books_avActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_books_avActionPerformed
        new BooksAvailable().setVisible(true);
    }//GEN-LAST:event_books_avActionPerformed

    private void contactusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactusActionPerformed
        new Contact().setVisible(true);
    }//GEN-LAST:event_contactusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbkBtn;
    private javax.swing.JButton adminBtn;
    private javax.swing.JButton books_av;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton closebtn;
    private javax.swing.JButton contactus;
    private javax.swing.JButton issuebkBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lgoutBtn;
    private javax.swing.JButton rtnBkBtn;
    private javax.swing.JButton studReg;
    // End of variables declaration//GEN-END:variables
}
