import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class StudentRegis extends javax.swing.JFrame {

    public StudentRegis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headlbl = new javax.swing.JLabel();
        courselbl = new javax.swing.JLabel();
        studname = new javax.swing.JLabel();
        phnlbl = new javax.swing.JLabel();
        branchlbl = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        lbleml = new javax.swing.JLabel();
        txteml = new javax.swing.JTextField();
        studid = new javax.swing.JLabel();
        txtcourse = new javax.swing.JTextField();
        txtbrch = new javax.swing.JTextField();
        txtphn = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 766));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headlbl.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        headlbl.setForeground(new java.awt.Color(0, 255, 255));
        headlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registration.jpeg"))); // NOI18N
        headlbl.setText("Student Registration");
        getContentPane().add(headlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 679, 68));

        courselbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        courselbl.setForeground(new java.awt.Color(240, 240, 240));
        courselbl.setText("Course");
        getContentPane().add(courselbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 176, 41));

        studname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        studname.setForeground(new java.awt.Color(240, 240, 240));
        studname.setText("Student Name");
        getContentPane().add(studname, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 176, 41));

        phnlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phnlbl.setForeground(new java.awt.Color(240, 240, 240));
        phnlbl.setText("Mobile no.");
        getContentPane().add(phnlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 176, 41));

        branchlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        branchlbl.setForeground(new java.awt.Color(240, 240, 240));
        branchlbl.setText("Branch");
        getContentPane().add(branchlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 176, 41));

        txtid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 466, 41));

        txtname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 466, 41));

        lbleml.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbleml.setForeground(new java.awt.Color(240, 240, 240));
        lbleml.setText("Email ID");
        getContentPane().add(lbleml, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 176, 41));

        txteml.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txteml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemlActionPerformed(evt);
            }
        });
        getContentPane().add(txteml, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 466, 41));

        studid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        studid.setForeground(new java.awt.Color(240, 240, 240));
        studid.setText("Student ID");
        getContentPane().add(studid, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 176, 41));

        txtcourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcourseActionPerformed(evt);
            }
        });
        getContentPane().add(txtcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 466, 41));

        txtbrch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtbrch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 466, 41));

        txtphn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtphn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphnActionPerformed(evt);
            }
        });
        getContentPane().add(txtphn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 466, 41));

        savebtn.setBackground(new java.awt.Color(0, 204, 0));
        savebtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        savebtn.setForeground(new java.awt.Color(255, 255, 255));
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        getContentPane().add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, 121, 41));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1370, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcourseActionPerformed

    private void txtphnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphnActionPerformed

    private void txtemlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemlActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        if(txtid.getText().equals("")){
            JOptionPane.showMessageDialog(this, "All feilds are required");
            txtid.requestFocus();
            
        }
        
        else if(txtname.getText().equals("")){
            JOptionPane.showMessageDialog(this, "All feilds are required");
            txtname.requestFocus();
        }
        
        else if(txtcourse.getText().equals("")){
            JOptionPane.showMessageDialog(this, "All feilds are required");
            txtcourse.requestFocus();
        }
        
        else if(txtbrch.getText().equals("")){
            JOptionPane.showMessageDialog(this, "All feilds are required");
            txtbrch.requestFocus();
        }
        
        else if(txtphn.getText().equals("")){
            JOptionPane.showMessageDialog(this, "All feilds are required");
            txtphn.requestFocus();
        }
        
        else if(txteml.getText().equals("")){
            JOptionPane.showMessageDialog(this, "All feilds are required");
            txteml.requestFocus();
        }
        
        else{
          Connection con;
            con = ConnectWithDB.Connection();
            try {
                PreparedStatement pst = con.prepareStatement("INSERT INTO STUDENT(id, name, course, branch, mobile, emailid) values(?, ?, ?, ?, ?, ?)");
                pst.setString(1, txtid.getText());
                pst.setString(2, txtname.getText());
                pst.setString(3, txtcourse.getText());
                pst.setString(4, txtbrch.getText());
                pst.setString(5, txtphn.getText());
                pst.setString(6, txteml.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Saved");
                txtid.setText("");
                txtname.setText("");
                txtcourse.setText("");
                txtbrch.setText("");
                txtphn.setText("");
                txteml.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(StudentRegis.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel branchlbl;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel courselbl;
    private javax.swing.JLabel headlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbleml;
    private javax.swing.JLabel phnlbl;
    private javax.swing.JButton savebtn;
    private javax.swing.JLabel studid;
    private javax.swing.JLabel studname;
    private javax.swing.JTextField txtbrch;
    private javax.swing.JTextField txtcourse;
    private javax.swing.JTextField txteml;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphn;
    // End of variables declaration//GEN-END:variables
}
